package infrastructure;

import java.lang.ScopedValue;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.sql.DataSource;

public class TransactionContext {

    private static final ScopedValue<Connection> CONNECTION = ScopedValue.newInstance();
    private static DataSource dataSource;

    public static void init(DataSource dataSource) {
        TransactionContext.dataSource = dataSource;
    }

    public static PreparedStatement getPreparedStatement(String sql) throws SQLException {
        return CONNECTION.get().prepareStatement(sql);
    }

    public static PreparedStatement getPreparedStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return CONNECTION.get().prepareStatement(sql, autoGeneratedKeys);
    }

    public static void run(TransactionalTask task) {
        try(Connection conn = dataSource.getConnection()){
            conn.setAutoCommit(false);
            ScopedValue.where(CONNECTION, conn).run(() -> {
                try {
                    task.execute();
                    conn.commit();
                } catch (SQLException e) {
                    rollbackQuietly(conn);
                    throw new RuntimeException(e);
                }
            });
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public static <T> T query(TransactionalQuery<T> query) {
        try (Connection conn = dataSource.getConnection()) {
            return ScopedValue.where(CONNECTION, conn).call(() -> {
                try {
                    return query.execute();
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            });
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static void rollbackQuietly(Connection conn) {
        try {
            conn.rollback();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private static Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }
}
