CREATE TABLE IF NOT EXISTS janggi_game (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(20) NOT NULL COMMENT '게임 상태',
    turn VARCHAR(10) NOT NULL COMMENT '현재 게임 턴',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS piece (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_id BIGINT NOT NULL,
    `row` INT NOT NULL COMMENT '행 좌표 (0~9)',
    `col` INT NOT NULL COMMENT '열 좌표 (0~8)',
    `type` VARCHAR(20) NOT NULL COMMENT '기물 종류)',
    `team` VARCHAR(20) NOT NULL COMMENT '진영',
    FOREIGN KEY (game_id) REFERENCES janggi_game(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_game_id ON piece(game_id);