package team.janggi.application;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.function.Function;
import team.janggi.config.AppConfig;

public class JdbcExecutor {
    private final TransactionManager transactionManager;

    public JdbcExecutor(TransactionManager transactionManager) {
        this.transactionManager = transactionManager;
    }

    public <T> T execute(String sql,
                         Function<PreparedStatement, T> action) {
        final Connection connection = transactionManager.getConnection();

        try {
            return action.apply(connection.prepareStatement(sql));
        } catch (SQLException e) {
          throw new RuntimeException("SQL 실행에 실패하였습니다.", e);
        } finally {
            close(connection);
        }
    }

    public <T> T execute(String sql,
                         int autoGeneratedKeys,
                         Function<PreparedStatement, T> action) {
        final Connection connection = transactionManager.getConnection();

        try {
            return action.apply(connection.prepareStatement(sql, autoGeneratedKeys));
        } catch (SQLException e) {
            throw new RuntimeException("SQL 실행에 실패하였습니다.", e);
        } finally {
            close(connection);
        }
    }

    private void close(Connection connection) {
        if (connection == null) {
            return;
        }
        try {
            // 트랜잭션이 관리하는 커넥션은 트랜잭션이 끝날 때 닫히므로, auto-commit이 켜져있는 커넥션만 닫는다.
            if (!connection.getAutoCommit()) {
                return;
            }
            connection.close();
        } catch (Exception e) {
            throw new RuntimeException("DB 연결을 닫는 과정에서 오류가 발생하였습니다.", e);
        }
    }
}
