plugins {
    id 'java'
}

version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:8.4.0'
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation platform('org.assertj:assertj-bom:3.27.3')
    testImplementation platform('org.testcontainers:testcontainers-bom:1.21.4')
    testImplementation('org.junit.jupiter:junit-jupiter')
    testImplementation('org.assertj:assertj-core')
    testImplementation('org.testcontainers:junit-jupiter')
    testImplementation('org.testcontainers:mysql')
    testImplementation 'org.slf4j:slf4j-nop:2.0.13'
}

processTestResources {
    from(layout.projectDirectory.file('schema.sql'))
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}
