CREATE TABLE GAME_ROOM(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
turn VARCHAR(10) NOT NULL,
title VARCHAR(50) NOT NULL,
state VARCHAR(20) NOT NULL
);

CREATE TABLE BOARD(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
team VARCHAR(10) NOT NULL,
piece_type VARCHAR(10) NOT NULL,
game_room_id BIGINT NOT NULL,
position_row TINYINT NOT NULL,
position_column TINYINT NOT NULL,
FOREIGN KEY (game_room_id) REFERENCES GAME_ROOM(id) ON DELETE CASCADE
);