CREATE TABLE IF NOT EXISTS game (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status BOOLEAN NOT NULL,
    turn_team VARCHAR(16) NOT NULL,
    cho_score DECIMAL(10, 1) NOT NULL,
    han_score DECIMAL(10, 1) NOT NULL,
    winner_team VARCHAR(16) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS piece (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_id BIGINT NOT NULL,
    team VARCHAR(16) NOT NULL,
    piece_type VARCHAR(32) NOT NULL,
    y INT NOT NULL,
    x INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_piece_game FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE
);
