CREATE TABLE IF NOT EXISTS GAME_ROOM (
     game_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     current_turn VARCHAR(20) NOT NULL,
     created_dt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BOARD (
     game_room_id BIGINT NOT NULL,
     position_x INT NOT NULL,
     position_y INT NOT NULL,
     piece_type VARCHAR(50) NOT NULL,
     team VARCHAR(20) NOT NULL,
     created_dt TIMESTAMP NOT NULL,
     updated_dt TIMESTAMP NOT NULL,

     PRIMARY KEY (game_room_id, position_x, position_y)
);