package db.jdbc;

import java.sql.PreparedStatement;
import java.sql.SQLException;

public interface SqlConnection {

    PreparedStatement prepareStatement(String sql) throws SQLException;

    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
}
