USE janggi;

CREATE TABLE IF NOT EXISTS player (
  name VARCHAR(10) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS game (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  status TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS game_player (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dynasty VARCHAR(10) NOT NULL,
  game_id BIGINT NOT NULL,
  player_name VARCHAR(10) NOT NULL,
  FOREIGN KEY (game_id) REFERENCES game(id),
  FOREIGN KEY (player_name) REFERENCES player(name)
);

CREATE TABLE IF NOT EXISTS piece (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  x INT NOT NULL,
  y INT NOT NULL,
  dynasty VARCHAR(10) NOT NULL,
  piece_type VARCHAR(10) NOT NULL,
  game_id BIGINT NOT NULL,
  FOREIGN KEY (game_id) REFERENCES game(id)
);