USE janggi;

CREATE TABLE IF NOT EXISTS game (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  status TINYINT DEFAULT 0,
  current_turn VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS piece (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  x INT NOT NULL,
  y INT NOT NULL,
  dynasty VARCHAR(10) NOT NULL,
  piece_type VARCHAR(10) NOT NULL,
  game_id BIGINT NOT NULL,
  FOREIGN KEY (game_id) REFERENCES game(id)
);