CREATE TABLE IF NOT EXISTS game (
    game_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_turn VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS piece (
    piece_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    piece_type VARCHAR(30) NOT NULL,
    position_row INT NOT NULL,
    position_column INT NOT NULL,
    team VARCHAR(30) NOT NULL,

    FOREIGN KEY (game_id) REFERENCES game(game_id) ON DELETE CASCADE,
    UNIQUE (game_id, position_row, position_column)
);