db.url=jdbc:h2:./janggi;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:/schema.sql'
db.username=sa
db.password=

# ???? ?? ?? ??? ?? ????? ?? ???? ??? ?? X
#  RUNSCRIPT FROM 'classpath:/init.sql'\\;\
#  RUNSCRIPT FROM 'classpath:/data.sql'
