create table if not exists game
(
    id bigint generated by default as identity,
    turn varchar(10),
    created_at timestamp default current_timestamp,
    primary key (id)
    );

create table if not exists piece
(
    id bigint generated by default as identity,
    game_id bigint,
    team varchar(10),
    piece_type varchar(50),
    x int,
    y int,
    primary key (id),
    foreign key (game_id) references game(id) on delete cascade
);
