CREATE TABLE IF NOT EXISTS game (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cho_player_name VARCHAR(5) NOT NULL,
    han_player_name VARCHAR(5) NOT NULL,
    cho_formation VARCHAR(30) NOT NULL,
    han_formation VARCHAR(30) NOT NULL,
    board_state CLOB NOT NULL,
    current_side VARCHAR(20) NOT NULL,
    move_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE game ADD COLUMN IF NOT EXISTS board_state CLOB DEFAULT '' NOT NULL;
ALTER TABLE game ADD COLUMN IF NOT EXISTS current_side VARCHAR(20) DEFAULT 'CHO' NOT NULL;
ALTER TABLE game ADD COLUMN IF NOT EXISTS move_count INT DEFAULT 0 NOT NULL;

CREATE INDEX IF NOT EXISTS idx_game_status ON game(status);
