CREATE TABLE IF NOT EXISTS game (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    turn VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS piece (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_id BIGINT NOT NULL,
    piece_type VARCHAR(20) NOT NULL,
    team VARCHAR(10) NOT NULL,
    position_x INT NOT NULL,
    position_y INT NOT NULL,
    FOREIGN KEY (game_id) REFERENCES game(id) ON DELETE CASCADE
);
