CREATE TABLE IF NOT EXISTS game_list
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      BIGINT UNIQUE NOT NULL,
    current_turn VARCHAR(5)    NOT NULL
);
CREATE TABLE IF NOT EXISTS piece
(
    game_id    BIGINT      NOT NULL,
    x          INT         NOT NULL,
    y          INT         NOT NULL,
    piece_type VARCHAR(20) NOT NULL,
    team       VARCHAR(5)  NOT NULL,
    CONSTRAINT fk_game_list FOREIGN KEY (game_id) REFERENCES game_list (game_id) ON DELETE CASCADE
);
