CREATE DATABASE IF NOT EXISTS janggi;

USE janggi;

CREATE TABLE IF NOT EXISTS game
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    is_end BOOLEAN     NOT NULL,
    turn   VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS piece
(
    id    INT AUTO_INCREMENT PRIMARY KEY,
    type  VARCHAR(20) NOT NULL,
    camp  VARCHAR(10) NOT NULL,
    pos_x INT         NOT NULL,
    pos_y INT         NOT NULL
);
