
CREATE TABLE PIECE
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    X       INT         NOT NULL,
    Y       INT         NOT NULL,
    TYPE    VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL
);

CREATE TABLE TURN
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    COUNTRY VARCHAR(20) NOT NULL
);
